# This system supports multiple banks.
# To create a new bank, simply copy-paste the `main` entry under it at the
# same level (with four spaces before), and updates the key (`main`, as this
# key must be unique) and the content.
#
# Example:
#
# banks:
#     main:
#         # The bank display name
#         name: "Main bank"
#
#         # The bank's location.
#         world: "world"
#         firstCorner: "-10,0,-10"
#         otherCorner: "10,60,10"
#
#        # The bank's center. If blank, the center of the area is used.
#        center: ""
#
#     other-bank:
#         # The bank display name
#         name: "Other bank"
#
#         # The bank's location.
#         world: "world"
#         firstCorner: "-100,0,-100"
#         otherCorner: "-60,120,-30"
#
#        # The bank's center. If blank, the center of the area is used.
#        center: ""
banks:
    main:
        # The bank display name
        name: "Main bank"

        # The bank's location.
        world: "world"
        firstCorner: "-10,0,-10"
        otherCorner: "10,60,10"

        # The bank's center. If blank, the center of the area is used.
        center: ""


# Item groups allows you to display in a separate UI grouped items.
# It allows a better global view of the stored amount of resources in your
# banks.
# As example, you can display a total of 21 for 1 block of iron and 12 ingots.
groups:
    - name: "Stone"
      icon: STONE
      relative_amounts:
          STONE: 1
          COBBLESTONE: 1

    - name: "Diamonds"
      icon: DIAMOND
      relative_amounts:
          DIAMOND_ORE: 1
          DIAMOND: 1
          DIAMOND_BLOCK: 9

    - name: "Gold"
      icon: GOLD_INGOT
      relative_amounts:
          GOLD_NUGGET: 0.111
          GOLD_ORE: 1
          GOLD_INGOT: 1
          GOLD_BLOCK: 9

    - name: "Iron"
      icon: IRON_INGOT
      relative_amounts:
          IRON_ORE: 1
          IRON_INGOT: 1
          IRON_BLOCK: 9

    - name: "Coal"
      icon: COAL
      relative_amounts:
          COAL_ORE: 1
          COAL: 1
          COAL_BLOCK: 9

    - name: "Lapis Lazuli"
      icon: INK_SACK_4
      relative_amounts:
          LAPIS_ORE: 6
          INK_SACK_4: 1
          LAPIS_BLOCK: 9

    - name: "Emerald"
      icon: EMERALD
      relative_amounts:
          EMERALD_ORE: 1
          EMERALD: 1
          EMERALD_BLOCK: 9

    - name: "Redstone"
      icon: REDSTONE
      relative_amounts:
          REDSTONE_ORE: 1
          REDSTONE: 1
          REDSTONE_BLOCK: 9

    - name: "Snow"
      icon: SNOW_BALL
      relative_amounts:
          SNOW_BALL: 1
          SNOW_BLOCK: 4

    - name: "Quartz"
      icon: QUARTZ
      relative_amounts:
          QUARTZ_ORE: 1
          QUARTZ: 1
          QUARTZ_BLOCK_0: 4

    - name: "Glowstone"
      icon: GLOWSTONE_DUST
      relative_amounts:
          GLOWSTONE_DUST: 1
          GLOWSTONE: 9

    - name: "Slime"
      icon: SLIME_BLOCK
      relative_amounts:
          SLIME_BALL: 1
          SLIME_BLOCK: 9

    - name: "Clay"
      icon: CLAY
      relative_amounts:
          CLAY: 1
          CLAY_BALL: 0.25
          HARD_CLAY: 1
          STAINED_CLAY: 1

    - name: "Paper"
      icon: PAPER
      relative_amounts:
          PAPER: 1
          SUGAR_CANE: 1

    - name: "Rails"
      icon: RAILS
      relative_amounts:
          RAILS: 1
          ACTIVATOR_RAIL: 1
          POWERED_RAIL: 1
          DETECTOR_RAIL: 1

    - name: "Minecarts"
      icon: MINECART
      relative_amounts:
          MINECART: 1
          STORAGE_MINECART: 1
          POWERED_MINECART: 1
          EXPLOSIVE_MINECART: 1
          HOPPER_MINECART: 1
          COMMAND_MINECART: 1

    - name: "Boats"
      icon: BOAT
      relative_amounts:
          BOAT: 1
          BOAT_SPRUCE: 1
          BOAT_BIRCH: 1
          BOAT_JUNGLE: 1
          BOAT_ACACIA: 1
          BOAT_DARK_OAK: 1

    - name: "Oak wood"
      icon: WOOD_0
      relative_amounts:
          WOOD_0: 1
          LOG_0: 4

    - name: "Spruce wood"
      icon: WOOD_1
      relative_amounts:
          WOOD_1: 1
          LOG_1: 4

    - name: "Birch wood"
      icon: WOOD_2
      relative_amounts:
          WOOD_2: 1
          "LOG:2": 4   # Cannot write LOG_2 because it would be interpreted as Material.LOG_2

    - name: "Jungle wood"
      icon: WOOD_3
      relative_amounts:
          WOOD_3: 1
          LOG_3: 4

    - name: "Acacia wood"
      icon: WOOD_0
      relative_amounts:
          WOOD_4: 1
          LOG_2_0: 4

    - name: "Dark Oak wood"
      icon: WOOD_5
      relative_amounts:
          WOOD_5: 1
          LOG_2_1: 4

    - name: "Apples"
      icon: APPLE
      relative_amounts:
          APPLE: 1
          GOLDEN_APPLE: 1

    - name: "Potatoes"
      icon: BAKED_POTATO
      relative_amounts:
          POTATO: 1
          BAKED_POTATO: 1

    - name: "Pork"
      icon: GRILLED_PORK
      relative_amounts:
          PORK: 1
          GRILLED_PORK: 1

    - name: "Beef"
      icon: COOKED_BEEF
      relative_amounts:
          RAW_BEEF: 1
          COOKED_BEEF: 1

    - name: "Chicken"
      icon: COOKED_CHICKEN
      relative_amounts:
          RAW_CHICKEN: 1
          COOKED_CHICKEN: 1

    - name: "Mutton"
      icon: COOKED_MUTTON
      relative_amounts:
          MUTTON: 1
          COOKED_MUTTON: 1

    - name: "Rabbit"
      icon: COOKED_RABBIT
      relative_amounts:
          RABBIT: 1
          COOKED_RABBIT: 1

    - name: "Fish"
      icon: COOKED_FISH
      relative_amounts:
          RAW_FISH: 1
          COOKED_FISH: 1


webservice:
    # If you want to use this with the web interface, set here the API base URL (without trailing slash).
    url: ""

    # Put here the authentification informations required.
    username: ""
    password: ""
